# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AOC

import flatbuffers

class Unit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUnit(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Unit()
        x.Init(buf, n + offset)
        return x

    # Unit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Unit
    def Common(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .CommonObjectInfo import CommonObjectInfo
            obj = CommonObjectInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Unit
    def ActionState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Unit
    def ActionTargetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Unit
    def ActionTargetPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Pos import Pos
            obj = Pos()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def UnitStart(builder): builder.StartObject(4)
def UnitAddCommon(builder, common): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(common), 0)
def UnitAddActionState(builder, actionState): builder.PrependInt8Slot(1, actionState, 0)
def UnitAddActionTargetId(builder, actionTargetId): builder.PrependInt32Slot(2, actionTargetId, 0)
def UnitAddActionTargetPos(builder, actionTargetPos): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(actionTargetPos), 0)
def UnitEnd(builder): return builder.EndObject()
