// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var AOC = AOC || {};

/**
 * @enum
 */
AOC.Restriction = {
  All: 0,
  InList: 1
};

/**
 * @enum
 */
AOC.ObjectState = {
  Ready: 0,
  Founded: 1,
  Alive: 2,
  Dying: 3,
  Dead: 4,
  Unknown1: 5,
  Unknown2: 6,
  Doppleganger: 7
};

/**
 * @enum
 */
AOC.TechState = {
  CantResearch: -1,
  CanResearchLater: 0,
  CanResearch: 1,
  Researching: 2,
  Researched: 3
};

/**
 * @enum
 */
AOC.ActionState = {
  None: 0,
  Done: 1,
  Wait: 2,
  Search: 3,
  GoTo: 4,
  Follow: 5,
  Attack: 6,
  GatherBuildAttack: 7,
  Dropoff: 8,
  Turn: 9,
  Delay: 10,
  Move: 11,
  ChopTree: 12,
  Failed: 13,
  Invalidated: 14,
  MoveNoSearch: 15
};

/**
 * @enum
 */
AOC.PlayerState = {
  Playing: 0,
  Winner: 1,
  Resigned: 2,
  Defeated: 3
};

/**
 * @constructor
 */
AOC.Pos = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.Pos}
 */
AOC.Pos.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
AOC.Pos.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
AOC.Pos.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
AOC.Pos.prototype.z = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
AOC.Pos.createPos = function(builder, x, y, z) {
  builder.prep(4, 12);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
AOC.UnitQueue = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.UnitQueue}
 */
AOC.UnitQueue.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
AOC.UnitQueue.prototype.unitType = function() {
  return this.bb.readInt16(this.bb_pos);
};

/**
 * @returns {number}
 */
AOC.UnitQueue.prototype.unitCount = function() {
  return this.bb.readInt16(this.bb_pos + 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} unitType
 * @param {number} unitCount
 * @returns {flatbuffers.Offset}
 */
AOC.UnitQueue.createUnitQueue = function(builder, unitType, unitCount) {
  builder.prep(2, 4);
  builder.writeInt16(unitCount);
  builder.writeInt16(unitType);
  return builder.offset();
};

/**
 * @constructor
 */
AOC.UnitTraining = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.UnitTraining}
 */
AOC.UnitTraining.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
AOC.UnitTraining.prototype.unitType = function() {
  return this.bb.readInt16(this.bb_pos);
};

/**
 * @returns {number}
 */
AOC.UnitTraining.prototype.timer = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} unitType
 * @param {number} timer
 * @returns {flatbuffers.Offset}
 */
AOC.UnitTraining.createUnitTraining = function(builder, unitType, timer) {
  builder.prep(4, 8);
  builder.writeFloat32(timer);
  builder.pad(2);
  builder.writeInt16(unitType);
  return builder.offset();
};

/**
 * @constructor
 */
AOC.MarketCoefficients = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.MarketCoefficients}
 */
AOC.MarketCoefficients.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
AOC.MarketCoefficients.prototype.wood = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
AOC.MarketCoefficients.prototype.food = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
AOC.MarketCoefficients.prototype.stone = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} wood
 * @param {number} food
 * @param {number} stone
 * @returns {flatbuffers.Offset}
 */
AOC.MarketCoefficients.createMarketCoefficients = function(builder, wood, food, stone) {
  builder.prep(4, 12);
  builder.writeFloat32(stone);
  builder.writeFloat32(food);
  builder.writeFloat32(wood);
  return builder.offset();
};

/**
 * @constructor
 */
AOC.Damage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.Damage}
 */
AOC.Damage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
AOC.Damage.prototype.gameTick = function() {
  return this.bb.readUint32(this.bb_pos);
};

/**
 * @returns {number}
 */
AOC.Damage.prototype.attackerId = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
AOC.Damage.prototype.projectileId = function() {
  return this.bb.readUint32(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
AOC.Damage.prototype.damagedId = function() {
  return this.bb.readInt32(this.bb_pos + 12);
};

/**
 * @returns {number}
 */
AOC.Damage.prototype.damageDone = function() {
  return this.bb.readFloat32(this.bb_pos + 16);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} gameTick
 * @param {number} attackerId
 * @param {number} projectileId
 * @param {number} damagedId
 * @param {number} damageDone
 * @returns {flatbuffers.Offset}
 */
AOC.Damage.createDamage = function(builder, gameTick, attackerId, projectileId, damagedId, damageDone) {
  builder.prep(4, 20);
  builder.writeFloat32(damageDone);
  builder.writeInt32(damagedId);
  builder.writeInt32(projectileId);
  builder.writeInt32(attackerId);
  builder.writeInt32(gameTick);
  return builder.offset();
};

/**
 * @constructor
 */
AOC.ProjectileFire = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.ProjectileFire}
 */
AOC.ProjectileFire.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
AOC.ProjectileFire.prototype.gameTick = function() {
  return this.bb.readUint32(this.bb_pos);
};

/**
 * @returns {number}
 */
AOC.ProjectileFire.prototype.projectileId = function() {
  return this.bb.readUint32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
AOC.ProjectileFire.prototype.sourceId = function() {
  return this.bb.readInt32(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
AOC.ProjectileFire.prototype.targetId = function() {
  return this.bb.readInt32(this.bb_pos + 12);
};

/**
 * @returns {number}
 */
AOC.ProjectileFire.prototype.type = function() {
  return this.bb.readInt16(this.bb_pos + 16);
};

/**
 * @returns {boolean}
 */
AOC.ProjectileFire.prototype.isPrimary = function() {
  return !!this.bb.readInt8(this.bb_pos + 18);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} gameTick
 * @param {number} projectileId
 * @param {number} sourceId
 * @param {number} targetId
 * @param {number} type
 * @param {boolean} isPrimary
 * @returns {flatbuffers.Offset}
 */
AOC.ProjectileFire.createProjectileFire = function(builder, gameTick, projectileId, sourceId, targetId, type, isPrimary) {
  builder.prep(4, 20);
  builder.pad(1);
  builder.writeInt8(+isPrimary);
  builder.writeInt16(type);
  builder.writeInt32(targetId);
  builder.writeInt32(sourceId);
  builder.writeInt32(projectileId);
  builder.writeInt32(gameTick);
  return builder.offset();
};

/**
 * @constructor
 */
AOC.ConfigMessage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.ConfigMessage}
 */
AOC.ConfigMessage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.ConfigMessage=} obj
 * @returns {AOC.ConfigMessage}
 */
AOC.ConfigMessage.getRootAsConfigMessage = function(bb, obj) {
  return (obj || new AOC.ConfigMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
AOC.ConfigMessage.prototype.tickInterval = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 500;
};

/**
 * @returns {number}
 */
AOC.ConfigMessage.prototype.mapObjectTickInterval = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 15000;
};

/**
 * @returns {number}
 */
AOC.ConfigMessage.prototype.updateCycles = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 1;
};

/**
 * @returns {AOC.Restriction}
 */
AOC.ConfigMessage.prototype.playerRestriction = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {AOC.Restriction} */ (this.bb.readInt8(this.bb_pos + offset)) : AOC.Restriction.All;
};

/**
 * @param {number} index
 * @returns {number}
 */
AOC.ConfigMessage.prototype.playerRestrictV = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
AOC.ConfigMessage.prototype.playerRestrictVLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
AOC.ConfigMessage.prototype.playerRestrictVArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {AOC.Restriction}
 */
AOC.ConfigMessage.prototype.objectRestriction = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? /** @type {AOC.Restriction} */ (this.bb.readInt8(this.bb_pos + offset)) : AOC.Restriction.All;
};

/**
 * @param {number} index
 * @returns {number}
 */
AOC.ConfigMessage.prototype.objectRestrictV = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
AOC.ConfigMessage.prototype.objectRestrictVLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint32Array}
 */
AOC.ConfigMessage.prototype.objectRestrictVArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? new Uint32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.ConfigMessage.startConfigMessage = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} tickInterval
 */
AOC.ConfigMessage.addTickInterval = function(builder, tickInterval) {
  builder.addFieldInt32(0, tickInterval, 500);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mapObjectTickInterval
 */
AOC.ConfigMessage.addMapObjectTickInterval = function(builder, mapObjectTickInterval) {
  builder.addFieldInt32(1, mapObjectTickInterval, 15000);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} updateCycles
 */
AOC.ConfigMessage.addUpdateCycles = function(builder, updateCycles) {
  builder.addFieldInt32(2, updateCycles, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {AOC.Restriction} playerRestriction
 */
AOC.ConfigMessage.addPlayerRestriction = function(builder, playerRestriction) {
  builder.addFieldInt8(3, playerRestriction, AOC.Restriction.All);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerRestrictVOffset
 */
AOC.ConfigMessage.addPlayerRestrictV = function(builder, playerRestrictVOffset) {
  builder.addFieldOffset(4, playerRestrictVOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
AOC.ConfigMessage.createPlayerRestrictVVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.ConfigMessage.startPlayerRestrictVVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {AOC.Restriction} objectRestriction
 */
AOC.ConfigMessage.addObjectRestriction = function(builder, objectRestriction) {
  builder.addFieldInt8(5, objectRestriction, AOC.Restriction.All);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectRestrictVOffset
 */
AOC.ConfigMessage.addObjectRestrictV = function(builder, objectRestrictVOffset) {
  builder.addFieldOffset(6, objectRestrictVOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
AOC.ConfigMessage.createObjectRestrictVVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.ConfigMessage.startObjectRestrictVVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.ConfigMessage.endConfigMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
AOC.ConfigMessage.finishConfigMessageBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
AOC.GameMessage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.GameMessage}
 */
AOC.GameMessage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.GameMessage=} obj
 * @returns {AOC.GameMessage}
 */
AOC.GameMessage.getRootAsGameMessage = function(bb, obj) {
  return (obj || new AOC.GameMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
AOC.GameMessage.prototype.tick = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
AOC.GameMessage.prototype.instanceGameNumber = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
AOC.GameMessage.prototype.finished = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {AOC.MarketCoefficients=} obj
 * @returns {AOC.MarketCoefficients|null}
 */
AOC.GameMessage.prototype.marketCoefficients = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new AOC.MarketCoefficients).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
AOC.GameMessage.prototype.mapName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {AOC.PlayerInfo=} obj
 * @returns {AOC.PlayerInfo}
 */
AOC.GameMessage.prototype.players = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new AOC.PlayerInfo).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.GameMessage.prototype.playersLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.PlayerObjects=} obj
 * @returns {AOC.PlayerObjects}
 */
AOC.GameMessage.prototype.objects = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new AOC.PlayerObjects).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.GameMessage.prototype.objectsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.ProjectileFire=} obj
 * @returns {AOC.ProjectileFire}
 */
AOC.GameMessage.prototype.projectilesFired = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? (obj || new AOC.ProjectileFire).__init(this.bb.__vector(this.bb_pos + offset) + index * 20, this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.GameMessage.prototype.projectilesFiredLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.Damage=} obj
 * @returns {AOC.Damage}
 */
AOC.GameMessage.prototype.damages = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? (obj || new AOC.Damage).__init(this.bb.__vector(this.bb_pos + offset) + index * 20, this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.GameMessage.prototype.damagesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.GameMessage.startGameMessage = function(builder) {
  builder.startObject(9);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} tick
 */
AOC.GameMessage.addTick = function(builder, tick) {
  builder.addFieldInt32(0, tick, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceGameNumber
 */
AOC.GameMessage.addInstanceGameNumber = function(builder, instanceGameNumber) {
  builder.addFieldInt32(1, instanceGameNumber, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} finished
 */
AOC.GameMessage.addFinished = function(builder, finished) {
  builder.addFieldInt8(2, +finished, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} marketCoefficientsOffset
 */
AOC.GameMessage.addMarketCoefficients = function(builder, marketCoefficientsOffset) {
  builder.addFieldStruct(3, marketCoefficientsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} mapNameOffset
 */
AOC.GameMessage.addMapName = function(builder, mapNameOffset) {
  builder.addFieldOffset(4, mapNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playersOffset
 */
AOC.GameMessage.addPlayers = function(builder, playersOffset) {
  builder.addFieldOffset(5, playersOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
AOC.GameMessage.createPlayersVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.GameMessage.startPlayersVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectsOffset
 */
AOC.GameMessage.addObjects = function(builder, objectsOffset) {
  builder.addFieldOffset(6, objectsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
AOC.GameMessage.createObjectsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.GameMessage.startObjectsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} projectilesFiredOffset
 */
AOC.GameMessage.addProjectilesFired = function(builder, projectilesFiredOffset) {
  builder.addFieldOffset(7, projectilesFiredOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.GameMessage.startProjectilesFiredVector = function(builder, numElems) {
  builder.startVector(20, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} damagesOffset
 */
AOC.GameMessage.addDamages = function(builder, damagesOffset) {
  builder.addFieldOffset(8, damagesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.GameMessage.startDamagesVector = function(builder, numElems) {
  builder.startVector(20, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.GameMessage.endGameMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.Tech = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.Tech}
 */
AOC.Tech.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.Tech=} obj
 * @returns {AOC.Tech}
 */
AOC.Tech.getRootAsTech = function(bb, obj) {
  return (obj || new AOC.Tech).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
AOC.Tech.prototype.techIdIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
AOC.Tech.prototype.techIdGame = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {AOC.TechState}
 */
AOC.Tech.prototype.techState = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {AOC.TechState} */ (this.bb.readInt16(this.bb_pos + offset)) : AOC.TechState.CanResearchLater;
};

/**
 * @returns {number}
 */
AOC.Tech.prototype.timePassed = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.Tech.startTech = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} techIdIndex
 */
AOC.Tech.addTechIdIndex = function(builder, techIdIndex) {
  builder.addFieldInt16(0, techIdIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} techIdGame
 */
AOC.Tech.addTechIdGame = function(builder, techIdGame) {
  builder.addFieldInt16(1, techIdGame, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {AOC.TechState} techState
 */
AOC.Tech.addTechState = function(builder, techState) {
  builder.addFieldInt16(2, techState, AOC.TechState.CanResearchLater);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} timePassed
 */
AOC.Tech.addTimePassed = function(builder, timePassed) {
  builder.addFieldFloat32(3, timePassed, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.Tech.endTech = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.PlayerInfo = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.PlayerInfo}
 */
AOC.PlayerInfo.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.PlayerInfo=} obj
 * @returns {AOC.PlayerInfo}
 */
AOC.PlayerInfo.getRootAsPlayerInfo = function(bb, obj) {
  return (obj || new AOC.PlayerInfo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.playerId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
AOC.PlayerInfo.prototype.playerName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {AOC.PlayerState}
 */
AOC.PlayerInfo.prototype.playerState = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {AOC.PlayerState} */ (this.bb.readInt8(this.bb_pos + offset)) : AOC.PlayerState.Playing;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.food = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.wood = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.stone = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.gold = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.headroom = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.population = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.populationCap = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.civilianPopulation = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.militaryPopulation = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.percentMapExplored = function() {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} index
 * @param {AOC.Tech=} obj
 * @returns {AOC.Tech}
 */
AOC.PlayerInfo.prototype.techs = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 30);
  return offset ? (obj || new AOC.Tech).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.techsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 30);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
AOC.PlayerInfo.prototype.mainSelected = function() {
  var offset = this.bb.__offset(this.bb_pos, 32);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.PlayerInfo.startPlayerInfo = function(builder) {
  builder.startObject(15);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} playerId
 */
AOC.PlayerInfo.addPlayerId = function(builder, playerId) {
  builder.addFieldInt8(0, playerId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} playerNameOffset
 */
AOC.PlayerInfo.addPlayerName = function(builder, playerNameOffset) {
  builder.addFieldOffset(1, playerNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {AOC.PlayerState} playerState
 */
AOC.PlayerInfo.addPlayerState = function(builder, playerState) {
  builder.addFieldInt8(2, playerState, AOC.PlayerState.Playing);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} food
 */
AOC.PlayerInfo.addFood = function(builder, food) {
  builder.addFieldFloat32(3, food, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} wood
 */
AOC.PlayerInfo.addWood = function(builder, wood) {
  builder.addFieldFloat32(4, wood, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} stone
 */
AOC.PlayerInfo.addStone = function(builder, stone) {
  builder.addFieldFloat32(5, stone, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} gold
 */
AOC.PlayerInfo.addGold = function(builder, gold) {
  builder.addFieldFloat32(6, gold, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} headroom
 */
AOC.PlayerInfo.addHeadroom = function(builder, headroom) {
  builder.addFieldFloat32(7, headroom, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} population
 */
AOC.PlayerInfo.addPopulation = function(builder, population) {
  builder.addFieldFloat32(8, population, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} populationCap
 */
AOC.PlayerInfo.addPopulationCap = function(builder, populationCap) {
  builder.addFieldFloat32(9, populationCap, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} civilianPopulation
 */
AOC.PlayerInfo.addCivilianPopulation = function(builder, civilianPopulation) {
  builder.addFieldFloat32(10, civilianPopulation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} militaryPopulation
 */
AOC.PlayerInfo.addMilitaryPopulation = function(builder, militaryPopulation) {
  builder.addFieldFloat32(11, militaryPopulation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} percentMapExplored
 */
AOC.PlayerInfo.addPercentMapExplored = function(builder, percentMapExplored) {
  builder.addFieldFloat32(12, percentMapExplored, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} techsOffset
 */
AOC.PlayerInfo.addTechs = function(builder, techsOffset) {
  builder.addFieldOffset(13, techsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
AOC.PlayerInfo.createTechsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.PlayerInfo.startTechsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mainSelected
 */
AOC.PlayerInfo.addMainSelected = function(builder, mainSelected) {
  builder.addFieldInt32(14, mainSelected, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.PlayerInfo.endPlayerInfo = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.PlayerObjects = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.PlayerObjects}
 */
AOC.PlayerObjects.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.PlayerObjects=} obj
 * @returns {AOC.PlayerObjects}
 */
AOC.PlayerObjects.getRootAsPlayerObjects = function(bb, obj) {
  return (obj || new AOC.PlayerObjects).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
AOC.PlayerObjects.prototype.playerId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.Building=} obj
 * @returns {AOC.Building}
 */
AOC.PlayerObjects.prototype.buildings = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new AOC.Building).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.PlayerObjects.prototype.buildingsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.Unit=} obj
 * @returns {AOC.Unit}
 */
AOC.PlayerObjects.prototype.units = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new AOC.Unit).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.PlayerObjects.prototype.unitsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.MapObject=} obj
 * @returns {AOC.MapObject}
 */
AOC.PlayerObjects.prototype.mapObjects = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new AOC.MapObject).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.PlayerObjects.prototype.mapObjectsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.PlayerObjects.startPlayerObjects = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} playerId
 */
AOC.PlayerObjects.addPlayerId = function(builder, playerId) {
  builder.addFieldInt8(0, playerId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} buildingsOffset
 */
AOC.PlayerObjects.addBuildings = function(builder, buildingsOffset) {
  builder.addFieldOffset(1, buildingsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
AOC.PlayerObjects.createBuildingsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.PlayerObjects.startBuildingsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} unitsOffset
 */
AOC.PlayerObjects.addUnits = function(builder, unitsOffset) {
  builder.addFieldOffset(2, unitsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
AOC.PlayerObjects.createUnitsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.PlayerObjects.startUnitsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} mapObjectsOffset
 */
AOC.PlayerObjects.addMapObjects = function(builder, mapObjectsOffset) {
  builder.addFieldOffset(3, mapObjectsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
AOC.PlayerObjects.createMapObjectsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.PlayerObjects.startMapObjectsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.PlayerObjects.endPlayerObjects = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.CommonObjectInfo = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.CommonObjectInfo}
 */
AOC.CommonObjectInfo.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.CommonObjectInfo=} obj
 * @returns {AOC.CommonObjectInfo}
 */
AOC.CommonObjectInfo.getRootAsCommonObjectInfo = function(bb, obj) {
  return (obj || new AOC.CommonObjectInfo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.objectId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.objectClass = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.objectType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
AOC.CommonObjectInfo.prototype.objectTypeName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {AOC.ObjectState}
 */
AOC.CommonObjectInfo.prototype.objectState = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? /** @type {AOC.ObjectState} */ (this.bb.readInt8(this.bb_pos + offset)) : AOC.ObjectState.Ready;
};

/**
 * @param {AOC.Pos=} obj
 * @returns {AOC.Pos|null}
 */
AOC.CommonObjectInfo.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new AOC.Pos).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.hp = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.maxHp = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.resourceType = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
AOC.CommonObjectInfo.prototype.resourceAmount = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.CommonObjectInfo.startCommonObjectInfo = function(builder) {
  builder.startObject(10);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} objectId
 */
AOC.CommonObjectInfo.addObjectId = function(builder, objectId) {
  builder.addFieldInt32(0, objectId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} objectClass
 */
AOC.CommonObjectInfo.addObjectClass = function(builder, objectClass) {
  builder.addFieldInt8(1, objectClass, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} objectType
 */
AOC.CommonObjectInfo.addObjectType = function(builder, objectType) {
  builder.addFieldInt16(2, objectType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectTypeNameOffset
 */
AOC.CommonObjectInfo.addObjectTypeName = function(builder, objectTypeNameOffset) {
  builder.addFieldOffset(3, objectTypeNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {AOC.ObjectState} objectState
 */
AOC.CommonObjectInfo.addObjectState = function(builder, objectState) {
  builder.addFieldInt8(4, objectState, AOC.ObjectState.Ready);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
AOC.CommonObjectInfo.addPos = function(builder, posOffset) {
  builder.addFieldStruct(5, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} hp
 */
AOC.CommonObjectInfo.addHp = function(builder, hp) {
  builder.addFieldFloat32(6, hp, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} maxHp
 */
AOC.CommonObjectInfo.addMaxHp = function(builder, maxHp) {
  builder.addFieldFloat32(7, maxHp, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} resourceType
 */
AOC.CommonObjectInfo.addResourceType = function(builder, resourceType) {
  builder.addFieldInt16(8, resourceType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} resourceAmount
 */
AOC.CommonObjectInfo.addResourceAmount = function(builder, resourceAmount) {
  builder.addFieldFloat32(9, resourceAmount, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.CommonObjectInfo.endCommonObjectInfo = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.Building = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.Building}
 */
AOC.Building.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.Building=} obj
 * @returns {AOC.Building}
 */
AOC.Building.getRootAsBuilding = function(bb, obj) {
  return (obj || new AOC.Building).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {AOC.CommonObjectInfo=} obj
 * @returns {AOC.CommonObjectInfo|null}
 */
AOC.Building.prototype.common = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new AOC.CommonObjectInfo).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.Building.prototype.researchingTechId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {AOC.UnitQueue=} obj
 * @returns {AOC.UnitQueue}
 */
AOC.Building.prototype.queue = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new AOC.UnitQueue).__init(this.bb.__vector(this.bb_pos + offset) + index * 4, this.bb) : null;
};

/**
 * @returns {number}
 */
AOC.Building.prototype.queueLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {AOC.UnitTraining=} obj
 * @returns {AOC.UnitTraining|null}
 */
AOC.Building.prototype.training = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new AOC.UnitTraining).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.Building.startBuilding = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} commonOffset
 */
AOC.Building.addCommon = function(builder, commonOffset) {
  builder.addFieldOffset(0, commonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} researchingTechId
 */
AOC.Building.addResearchingTechId = function(builder, researchingTechId) {
  builder.addFieldInt16(1, researchingTechId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} queueOffset
 */
AOC.Building.addQueue = function(builder, queueOffset) {
  builder.addFieldOffset(2, queueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
AOC.Building.startQueueVector = function(builder, numElems) {
  builder.startVector(4, numElems, 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} trainingOffset
 */
AOC.Building.addTraining = function(builder, trainingOffset) {
  builder.addFieldStruct(3, trainingOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.Building.endBuilding = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.Unit = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.Unit}
 */
AOC.Unit.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.Unit=} obj
 * @returns {AOC.Unit}
 */
AOC.Unit.getRootAsUnit = function(bb, obj) {
  return (obj || new AOC.Unit).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {AOC.CommonObjectInfo=} obj
 * @returns {AOC.CommonObjectInfo|null}
 */
AOC.Unit.prototype.common = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new AOC.CommonObjectInfo).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {AOC.ActionState}
 */
AOC.Unit.prototype.actionState = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {AOC.ActionState} */ (this.bb.readInt8(this.bb_pos + offset)) : AOC.ActionState.None;
};

/**
 * @returns {number}
 */
AOC.Unit.prototype.actionTargetId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {AOC.Pos=} obj
 * @returns {AOC.Pos|null}
 */
AOC.Unit.prototype.actionTargetPos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new AOC.Pos).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.Unit.startUnit = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} commonOffset
 */
AOC.Unit.addCommon = function(builder, commonOffset) {
  builder.addFieldOffset(0, commonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {AOC.ActionState} actionState
 */
AOC.Unit.addActionState = function(builder, actionState) {
  builder.addFieldInt8(1, actionState, AOC.ActionState.None);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} actionTargetId
 */
AOC.Unit.addActionTargetId = function(builder, actionTargetId) {
  builder.addFieldInt32(2, actionTargetId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} actionTargetPosOffset
 */
AOC.Unit.addActionTargetPos = function(builder, actionTargetPosOffset) {
  builder.addFieldStruct(3, actionTargetPosOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.Unit.endUnit = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
AOC.MapObject = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {AOC.MapObject}
 */
AOC.MapObject.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {AOC.MapObject=} obj
 * @returns {AOC.MapObject}
 */
AOC.MapObject.getRootAsMapObject = function(bb, obj) {
  return (obj || new AOC.MapObject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {AOC.CommonObjectInfo=} obj
 * @returns {AOC.CommonObjectInfo|null}
 */
AOC.MapObject.prototype.common = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new AOC.CommonObjectInfo).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
AOC.MapObject.startMapObject = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} commonOffset
 */
AOC.MapObject.addCommon = function(builder, commonOffset) {
  builder.addFieldOffset(0, commonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
AOC.MapObject.endMapObject = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.AOC = AOC;
