# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AOC

import flatbuffers

class UnitQueue(object):
    __slots__ = ['_tab']

    # UnitQueue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnitQueue
    def UnitType(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # UnitQueue
    def UnitCount(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateUnitQueue(builder, unitType, unitCount):
    builder.Prep(2, 4)
    builder.PrependInt16(unitCount)
    builder.PrependInt16(unitType)
    return builder.Offset()
