# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AOC

class ActionState(object):
    None_ = 0
    Done = 1
    Wait = 2
    Search = 3
    GoTo = 4
    Follow = 5
    Attack = 6
    GatherBuildAttack = 7
    Dropoff = 8
    Turn = 9
    Delay = 10
    Move = 11
    ChopTree = 12
    Failed = 13
    Invalidated = 14
    MoveNoSearch = 15

