# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AOC

import flatbuffers

class GameMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGameMessage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameMessage()
        x.Init(buf, n + offset)
        return x

    # GameMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GameMessage
    def Tick(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GameMessage
    def InstanceGameNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GameMessage
    def Finished(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GameMessage
    def MarketCoefficients(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .MarketCoefficients import MarketCoefficients
            obj = MarketCoefficients()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMessage
    def MapName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GameMessage
    def Players(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PlayerInfo import PlayerInfo
            obj = PlayerInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMessage
    def PlayersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMessage
    def Objects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PlayerObjects import PlayerObjects
            obj = PlayerObjects()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMessage
    def ObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMessage
    def ProjectilesFired(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            from .ProjectileFire import ProjectileFire
            obj = ProjectileFire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMessage
    def ProjectilesFiredLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMessage
    def Damages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            from .Damage import Damage
            obj = Damage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameMessage
    def DamagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GameMessageStart(builder): builder.StartObject(9)
def GameMessageAddTick(builder, tick): builder.PrependUint32Slot(0, tick, 0)
def GameMessageAddInstanceGameNumber(builder, instanceGameNumber): builder.PrependUint32Slot(1, instanceGameNumber, 0)
def GameMessageAddFinished(builder, finished): builder.PrependBoolSlot(2, finished, 0)
def GameMessageAddMarketCoefficients(builder, marketCoefficients): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(marketCoefficients), 0)
def GameMessageAddMapName(builder, mapName): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)
def GameMessageAddPlayers(builder, players): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(players), 0)
def GameMessageStartPlayersVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GameMessageAddObjects(builder, objects): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(objects), 0)
def GameMessageStartObjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GameMessageAddProjectilesFired(builder, projectilesFired): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(projectilesFired), 0)
def GameMessageStartProjectilesFiredVector(builder, numElems): return builder.StartVector(20, numElems, 4)
def GameMessageAddDamages(builder, damages): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(damages), 0)
def GameMessageStartDamagesVector(builder, numElems): return builder.StartVector(20, numElems, 4)
def GameMessageEnd(builder): return builder.EndObject()
