# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AOC

class TechState(object):
    CantResearch = -1
    CanResearchLater = 0
    CanResearch = 1
    Researching = 2
    Researched = 3

